spring.application.name=thesis
spring.datasource.url=jdbc:mysql://localhost:3306/thesis
spring.datasource.username=root
spring.datasource.password=Pitou111122223333
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true